### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by SvartUlv** [NatLibFi/marc-record-validate#4]
I'm not sure if I'm getting it right. I would be very grateful if you could provide a complete example of creating a MARC record from a string, validating(e.g. DoubleCommas) and getting the results.

**Comment by ghost** [comment]
Hi. I made the instructions more explicit. The [@natlibfi/marc-record](https://www.npmjs.com/package/@natlibfi/marc-record) README should get you started on creating records. Also see [@natlibfi/marc-record-serializers](https://www.npmjs.com/package/@natlibfi/marc-record-serializers).

**Comment by SvartUlv** [comment]
Hi, thank you very much for the explanation. Now I'am struggling with the following errors and I will appreciate any help.

### First
```
import MarcRecord from '@natlibfi/marc-record';
const record = new MarcRecord();
```

`npm run build`

```
ERROR in ./node_modules/@natlibfi/marc-record/dist/utils.js
Module not found: Error: Can't resolve 'fs' in '/home/nuadmin/marc_validation/node_modules/@natlibfi/marc-record/dist'
 @ ./node_modules/@natlibfi/marc-record/dist/utils.js 1:138-151
 @ ./node_modules/@natlibfi/marc-record/dist/index.js
 @ ./src/js/index.js
```
*It works with "marc-record-js"

### Second

```
import {DoubleCommas} from '@natlibfi/marc-record-validators-melinda';
import validateFactory from '@natlibfi/marc-record-validate';
const validate = validateFactory([await DoubleCommas()]);
```

`npm run build `
```
ERROR in ./src/js/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: await is a reserved word (3:34)
```

### My configuration

- Ubuntu 16.04
- Node 8.11.4
- npm 5.6.0
- package.json
```
{
  "name": "marc_validation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --config webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "webpack": "^4.17.2",
    "webpack-cli": "^3.1.0"
  },
  "dependencies": {
    "@natlibfi/marc-record": "^2.0.1",
    "@natlibfi/marc-record-validate": "^3.0.1",
    "@natlibfi/marc-record-validators-melinda": "^3.1.1",
    "marc-record-js": "^0.3.2"
  }
}
```
- .babelrc
```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": "last 2 versions"
        }
      }
    ]
  ]
}
```
- webpack.config.js
```
const path = require("path");

module.exports = {
  mode: 'development',
  entry: "./src/js/index.js",
  output: {
    path: path.resolve(__dirname, "public/js"),
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["babel-preset-env"]
          }
        }
      }
    ]
  }
};
```

**Comment by ghost** [comment]
All right:

## MarcRecord
Two things. First: The import example in the README is wrong, it should be: `import {MarcRecord} from '@natlibfi/marc-record'`. I fixed that.
     
 Second: As you are building for browser using webpack, you need to somehow shim node-specific APIs. I'm not an expert on webpack but this option (In webpack config) might help: `target: 'node'`

Please let me know how you get it to work, if you do :)

## await is a reserved word
You cannot use `await` in top-level code. It needs to be wrapped in an async function (At least on Node). I fixed the README accordingly.

**Comment by SvartUlv** [comment]
I'm moving slowly forward ;) I'm also not an expert on webpack. Do you recommend some other tools?
My purpose is to combine those two scripts(marc-record, marc-record-validate) and use them in a browser.

**Comment by ghost** [comment]
It seems the code and the dependencies are not really browser-compatible even with Webpack. I'll look into this and try to get back you during this week.

**Comment by SvartUlv** [comment]
Thank you very much for help. Those scripts looks very useful but I want to use them in a browser that users could validate records(marc21 text version) by themselves.

**Comment by ghost** [comment]
Now all the modules are browser-compatible (Be sure to use the newest versions of \@natlibfi/marc-record and \@natlibfi/marc-record-validators-melinda). Here's a reference package.json and Webpack config:
```js
{
  "name": "wp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "dependencies": {
    "@natlibfi/marc-record": "^2.1.1",
    "@natlibfi/marc-record-validate": "^3.0.3",
    "@natlibfi/marc-record-validators-melinda": "^4.0.0",
    "babel-polyfill": "^6.26.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "webpack": "^4.18.0",
    "webpack-cli": "^3.1.0"
  }
}
```
```js
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  node: {
    fs: 'empty'
  },
  resolve: {
    alias: {
      'beautify-isbn': path.join(__dirname, 'node_modules', 'beautify-isbn', 'dist', 'bundle.cjs.js')
    }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  }
};
```

**Comment by SvartUlv** [comment]
It works! :) Thanks a lot!

I just had to add "babel-polyfill" in entry
`entry: ['babel-polyfill','./src/index.js'],`

**Comment by SvartUlv** [comment]
One more thing. Import should be inside a function?

```
async function run() {
  import {DoubleCommas} from '@natlibfi/marc-record-validators-melinda';
  import validateFactory from '@natlibfi/marc-record-validate';
  ...
}
```
I got: 

`'import' and 'export' may only appear at the top level`

**Comment by ghost** [comment]
You're right. I fixed that in the README.

**Comment by SvartUlv** [comment]
Ok. Thanks ;)
